# Generated by Django 2.1.7 on 2019-04-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='district',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='province',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(max_length=100, verbose_name='收货地址'),
        ),
    ]
