# Generated by Django 2.1.7 on 2019-07-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_usercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='express',
            field=models.IntegerField(verbose_name='物流'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='quality',
            field=models.IntegerField(verbose_name='质量'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='service',
            field=models.IntegerField(verbose_name='服务'),
        ),
    ]
