# Generated by Django 2.1.7 on 2019-07-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0005_auto_20190701_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomment',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='评论'),
        ),
    ]
