# Generated by Django 2.1.7 on 2019-04-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='totalPrice',
            field=models.IntegerField(default=0, verbose_name='总价'),
        ),
    ]
