# Generated by Django 2.1.7 on 2019-04-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_shoppingcart_totalprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='post_script',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='trade_no',
        ),
    ]
