# Generated by Django 2.1.7 on 2019-04-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190417_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='totalPrice',
            field=models.FloatField(default=0.0, verbose_name='总价'),
        ),
    ]
