# Generated by Django 2.1.7 on 2019-04-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20190417_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='pay_time',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='create_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='创建时间'),
        ),
    ]
