# Generated by Django 2.1.7 on 2019-06-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20190418_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.IntegerField(verbose_name='订单信息'),
        ),
    ]
