# Generated by Django 2.1.7 on 2019-06-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20190627_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='goods',
            field=models.CharField(max_length=50, verbose_name='商品'),
        ),
    ]
