# Generated by Django 2.1.7 on 2019-06-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20190627_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='order',
            field=models.IntegerField(max_length=50, verbose_name='订单信息'),
        ),
    ]
