# Generated by Django 2.1.7 on 2019-06-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_ordergoods_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='totalprice',
            field=models.IntegerField(default=0, verbose_name='小计'),
        ),
    ]
