# Generated by Django 2.1.7 on 2019-07-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_finishedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='comment',
            field=models.CharField(default='undone', max_length=20, verbose_name='评论状态'),
        ),
    ]
