# Generated by Django 2.1.7 on 2019-07-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0015_aftersale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aftersale',
            name='number',
            field=models.CharField(max_length=20, verbose_name='物流单号'),
        ),
    ]
