# Generated by Django 2.1.7 on 2019-07-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_auto_20190703_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftersale',
            name='event',
            field=models.CharField(default='退货', max_length=10, verbose_name='事务'),
            preserve_default=False,
        ),
    ]
